apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./crds
- ./service_account.yaml
- ./role.yaml
- ./cluster_role_binding.yaml
- ./operator-vpavlin.yaml
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: kubeflow-operator

configurations:
- ./params.yaml
namespace: kubeflow-operator
